name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    name: Deploy
    steps:
      - uses: actions/checkout@v4

      - name: Create Toml File
        run: |
          cat << EOF >> wrangler.toml
          name = "warload_archives_api"
          compatibility_date = "2023-12-01"
          main = "src/index.ts"
          [[d1_databases]]
          binding = "DB"
          database_name = "${{ secrets.D1_DB_NAME }}"
          database_id = "${{ secrets.D1_DB_ID }}"
          migrations_dir = "src/drizzle/migrations"
          EOF

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_TOKEN }}
