name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    name: Deploy
    steps:
      - uses: actions/checkout@v4

      - name: Create Toml File
        run: |
          echo 'name = "warload_archives_api"' >> wrangler.toml
          echo 'compatibility_date = "2023-12-01"' >> wrangler.toml
          echo 'main = "src/index.ts"' >> wrangler.toml
          echo 'account_id = "${{ secrets.CLOUDFLARE_ACCOUNT_ID }}"' >> wrangler.toml

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_TOKEN }}
